#!/usr/bin/env python3
"""Show the current state of this project's tasks, hiding archived ones.

Generated by the flowai `tasks-overview` skill from its bundled template.
The SCHEMA block marked below is the only project-specific part: it says
where the task files live, which frontmatter key holds the status, which
values mean "archived", and which section carries the progress checkboxes.
The block is text that the script parses itself (not Python it executes), so
a typo there is reported as a schema error with exit 2 instead of a
traceback. Edit the block by hand when the project's task convention
changes; the rest of the file is plain scanning logic and needs nothing but
Python 3.

Usage:
    python3 scripts/tasks-overview.py          # open tasks only
    python3 scripts/tasks-overview.py --all    # archived tasks too

Exit codes: 0 — listed; 2 — the task root is missing, the schema block is
malformed, or a task file could not be read (the message names the path).
"""

import ast
import re
import sys
from pathlib import Path

SCHEMA_TEXT = r'''
# --- SCHEMA BEGIN ---
SCHEMA = {
    # Directory that holds the task files, relative to the project root.
    "root": "documents/tasks",
    # Glob relative to `root` that selects task files.
    "pattern": "**/*.md",
    # File names inside `root` that are not tasks.
    "ignore": ["README.md"],
    # Frontmatter key that carries the task status.
    "status_key": "status",
    # Status shown for a file whose frontmatter has no status key.
    "missing_status": "unknown",
    # Status values that hide a task unless `--all` is given.
    "archived_statuses": ["done", "superseded"],
    # Subdirectories of `root` whose files are archived whatever their status.
    "archived_dirs": [],
    # Heading whose top-level `- [ ]` / `- [x]` items give the progress, or None.
    "progress_section": "## Definition of Done",
}
# --- SCHEMA END ---
'''

REQUIRED_KEYS = (
    "root",
    "pattern",
    "ignore",
    "status_key",
    "missing_status",
    "archived_statuses",
    "archived_dirs",
    "progress_section",
)

CHECKBOX_RE = re.compile(r"^- \[( |x|X)\] ")
HEADING_RE = re.compile(r"^#{1,6} ")


def fail(message):
    print(f"tasks-overview: {message}", file=sys.stderr)
    return 2


def warn(message):
    print(f"tasks-overview: warning: {message}", file=sys.stderr)


def load_schema(text):
    """Parse the SCHEMA block; return (schema, problem) with one of them None."""
    begin = "# --- SCHEMA BEGIN ---"
    end = "# --- SCHEMA END ---"
    a = text.find(begin)
    b = text.find(end)
    if a < 0 or b < a:
        return None, "schema block markers are missing"
    body = text[a + len(begin):b].strip()
    prefix = "SCHEMA ="
    if not body.startswith(prefix):
        return None, "schema block must start with 'SCHEMA = {'"
    try:
        schema = ast.literal_eval(body[len(prefix):].strip())
    except (SyntaxError, ValueError) as error:
        return None, f"schema block is not a valid Python dict literal: {error}"
    return schema, validate_schema(schema)


def validate_schema(schema):
    if not isinstance(schema, dict):
        return "schema block is not a dict"
    missing = [k for k in REQUIRED_KEYS if k not in schema]
    if missing:
        return "schema block lacks keys: " + ", ".join(missing)
    for key in ("ignore", "archived_statuses", "archived_dirs"):
        if not isinstance(schema[key], list):
            return f"schema key {key!r} must be a list"
    return None


def parse_scalar(raw):
    value = raw.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[1:-1]
    return value


def parse_inline_list(raw):
    text = raw.strip()
    start = text.find("[")
    end = text.rfind("]")
    if start == -1 or end < start:
        return []
    inner = text[start + 1:end].strip()
    if not inner:
        return []
    # A trailing comma leaves an empty part behind. `deno fmt` writes one on
    # every list it wraps, so dropping empty parts is not an edge case here.
    return [parse_scalar(part) for part in inner.split(",") if part.strip()]


def gather_flow(lines, start, text):
    """Collect a `[...]` sequence that may be wrapped over several lines.

    A formatter wraps a long list onto its own indented lines and leaves a
    trailing comma behind, which is what most `related_tasks:` keys in this
    repository look like. Returns (the whole sequence on one line, the index
    of the line after it), or (None, start) when the brackets never balance
    before the frontmatter ends — the caller then reports the line as it did
    before.
    """
    parts = []
    depth = 0
    cursor = start
    current = text
    while True:
        parts.append(current)
        depth += current.count("[") - current.count("]")
        if depth <= 0:
            return " ".join(parts), cursor + 1
        cursor += 1
        if cursor >= len(lines) or lines[cursor].strip() == "---":
            return None, start
        current = lines[cursor].strip()


def parse_frontmatter(lines, path):
    """Return (frontmatter dict, index of the first body line).

    Handles the YAML subset task files use: `key: value`, `key: [a, b]`,
    and block lists (`key:` followed by `  - item` lines). Anything else is
    reported on stderr with its line number and skipped.
    """
    if not lines or lines[0].strip() != "---":
        return {}, 0
    data = {}
    current_list = None
    index = 1
    while index < len(lines):
        line = lines[index]
        if line.strip() == "---":
            return data, index + 1
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            index += 1
            continue
        if current_list is not None and stripped.startswith("- "):
            current_list.append(parse_scalar(stripped[2:]))
            index += 1
            continue
        current_list = None
        key, sep, rest = line.partition(":")
        if not sep or line.startswith((" ", "\t")):
            warn(f"{path}:{index + 1}: cannot parse frontmatter line: {stripped}")
            index += 1
            continue
        key = key.strip()
        rest = rest.strip()
        if rest.startswith("["):
            flow, after = gather_flow(lines, index, rest)
            if flow is None:
                warn(f"{path}:{index + 1}: cannot parse frontmatter line: {stripped}")
                index += 1
                continue
            data[key] = parse_inline_list(flow)
            index = after
            continue
        if rest == "":
            # `key:` on its own opens a block list — unless what follows is a
            # flow sequence wrapped onto the next lines, which reads as an
            # indented `[` and is not a list item.
            probe = index + 1
            while probe < len(lines) and not lines[probe].strip():
                probe += 1
            if probe < len(lines) and lines[probe].strip().startswith("["):
                flow, after = gather_flow(lines, probe, lines[probe].strip())
                if flow is not None:
                    data[key] = parse_inline_list(flow)
                    index = after
                    continue
            current_list = []
            data[key] = current_list
        else:
            data[key] = parse_scalar(rest)
        index += 1
    warn(f"{path}: frontmatter is not closed")
    return data, len(lines)


def find_title(lines, start, fallback):
    for line in lines[start:]:
        if line.startswith("# "):
            return line[2:].strip()
    return fallback


def count_progress(lines, start, heading):
    if heading is None:
        return None
    inside = False
    total = 0
    checked = 0
    for line in lines[start:]:
        if HEADING_RE.match(line):
            if inside:
                break
            inside = line.strip() == heading
            continue
        if not inside:
            continue
        match = CHECKBOX_RE.match(line)
        if match:
            total += 1
            if match.group(1) in "xX":
                checked += 1
    if total == 0:
        return None
    return checked, total


def as_text(value):
    if isinstance(value, list):
        return ", ".join(str(v) for v in value)
    return str(value)


def scan(schema, project_root):
    root = project_root / schema["root"]
    if not root.is_dir():
        raise FileNotFoundError(f"task root {schema['root']} not found under {project_root}")
    archived_dirs = [root / d for d in schema["archived_dirs"]]
    tasks = []
    for file in sorted(root.glob(schema["pattern"])):
        if not file.is_file() or file.name in schema["ignore"]:
            continue
        try:
            lines = file.read_text(encoding="utf-8").splitlines()
        except OSError as error:
            raise OSError(f"cannot read {file}: {error}") from error
        rel = file.relative_to(project_root).as_posix()
        data, body_start = parse_frontmatter(lines, rel)
        status = data.get(schema["status_key"], schema["missing_status"])
        status = as_text(status)
        in_archive_dir = any(file.is_relative_to(d) for d in archived_dirs)
        tasks.append({
            "path": rel,
            "title": find_title(lines, body_start, file.stem),
            "status": status,
            "date": as_text(data.get("date", "")),
            "implements": as_text(data.get("implements", "")),
            "progress": count_progress(lines, body_start, schema["progress_section"]),
            "archived": in_archive_dir or status in schema["archived_statuses"],
        })
    return tasks


def status_rank(status):
    preferred = ["in progress", "to do"]
    if status in preferred:
        return (0, preferred.index(status), status)
    return (1, 0, status)


def render(tasks, show_all):
    open_tasks = [t for t in tasks if not t["archived"]]
    hidden = len(tasks) - len(open_tasks)
    shown = tasks if show_all else open_tasks
    groups = {}
    for t in shown:
        groups.setdefault(t["status"], []).append(t)
    out = []
    for status in sorted(groups, key=status_rank):
        items = sorted(groups[status], key=lambda t: t["date"], reverse=True)
        label = f"{status} ({len(items)})"
        out.append(label)
        out.append("-" * len(label))
        for t in items:
            columns = [t["path"]]
            if t["progress"] is not None:
                done, total = t["progress"]
                columns.append(f"[{done}/{total}]")
            columns.append(t["title"])
            details = [d for d in (t["date"], t["implements"]) if d]
            if details:
                columns.append("(" + "; ".join(details) + ")")
            out.append("  " + "  ".join(columns))
        out.append("")
    footer = f"{len(open_tasks)} open"
    if show_all:
        footer += f", {hidden} archived (shown)"
    else:
        footer += f", {hidden} archived (hidden; use --all)"
    out.append(footer)
    return "\n".join(out)


def main(argv):
    show_all = "--all" in argv
    unknown = [a for a in argv if a not in ("--all",)]
    if unknown:
        return fail("unknown argument(s): " + " ".join(unknown) + " (only --all is accepted)")
    schema, problem = load_schema(SCHEMA_TEXT)
    if problem:
        return fail(problem)
    project_root = Path.cwd()
    try:
        tasks = scan(schema, project_root)
    except (FileNotFoundError, OSError) as error:
        return fail(str(error))
    if not tasks:
        print(f"no tasks under {schema['root']}")
        return 0
    print(render(tasks, show_all))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
